#remote_theme: mmistakes/minimal-mistakes@4.27.3
remote_theme: jekyll/minima

title: Gull Group
description: Computational Quantum Many-Body Theory — University of Warsaw

header_pages:
  - research.md
  - people.md
  - publications.md
  - software.md
  - outreach.md
  - positions.md

minima:
  hide_site_feed_link: true

plugins:
 - jekyll-remote-theme
 - jekyll-include-cache

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true
google_analytics: G-5VZDLTCMDW
